version: '3'
services:

  app:
    build: .
    ports:
      - 8000:4000
    volumes:
      - ./src:/webapp
      - ./weights:/weights
    command: gunicorn -b 0.0.0.0:4000 webapp.app:app --chdir / --reload
    environment:
      - PYTHONUNBUFFERED=1

  tesseract:
    image: sdlmer/tesseract-api

  chineseocr:
    image: zergmk2/chineseocr:pytorch1.0-cpu-py3.6
